version: '3.8'
services:

  postgres:
    container_name: database-teste
    image: postgres:13.5
    restart: unless-stopped

    environment:
        POSTGRES_USER: testdatabase
        POSTGRES_PASSWORD: password
        POSTGRES_DB: development
        PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'

volumes:
  postgres: